"""Load tests for DormChef API.

Run:
    poetry run locust -f locustfile.py --headless \
        -u 50 -r 5 -t 30s --host http://localhost:8000
"""

from __future__ import annotations

from locust import HttpUser
from locust import between
from locust import task


class DormChefUser(HttpUser):
    """Simulated user for DormChef load testing."""

    wait_time = between(0.5, 2.0)

    def on_start(self) -> None:
        """Seed a recipe so GET and search have data to work with."""
        self.client.post(
            "/recipes",
            json={
                "title": "Load Test Pasta",
                "description": "Quick pasta for load testing",
                "ingredients": ["pasta", "tomato", "salt"],
                "steps": ["Boil water", "Cook pasta", "Add sauce"],
            },
        )

    @task(3)
    def list_recipes(self) -> None:
        """GET /recipes — most common operation."""
        self.client.get("/recipes")

    @task(2)
    def search_recipes(self) -> None:
        """GET /recipes/search — search by ingredient."""
        self.client.get(
            "/recipes/search",
            params={"ingredients": "pasta,tomato"},
        )

    @task(1)
    def create_recipe(self) -> None:
        """POST /recipes — less frequent write."""
        self.client.post(
            "/recipes",
            json={
                "title": "Locust Recipe",
                "description": "Generated by load test",
                "ingredients": ["egg", "cheese"],
                "steps": ["Crack egg", "Add cheese", "Cook"],
            },
        )
