"""Load tests for DormChef API.

All tasks (default):

    poetry run locust -f locustfile.py --headless \\
        -u 50 -r 5 -t 30s --host http://localhost:8000

Internal API only (``/recipes``, ``/recipes/search``):

    poetry run locust -f locustfile.py --headless --tags internal \\
        -u 50 -r 5 -t 30s --host http://localhost:8000

TheMealDB routes only (lower ``-u`` recommended):

    poetry run locust -f locustfile.py --headless --tags external \\
        -u 20 -r 2 -t 30s --host http://localhost:8000
"""

from __future__ import annotations

from locust import HttpUser
from locust import between
from locust import tag
from locust import task

_MEALDB_SAMPLE_MEAL_ID = "52772"


class DormChefUser(HttpUser):
    """Simulated user for DormChef load testing."""

    wait_time = between(0.5, 2.0)

    def on_start(self) -> None:
        """Seed a recipe so GET and search have data to work with."""
        self.client.post(
            "/recipes",
            json={
                "title": "Load Test Pasta",
                "description": "Quick pasta for load testing",
                "ingredients": ["pasta", "tomato", "salt"],
                "steps": ["Boil water", "Cook pasta", "Add sauce"],
            },
        )

    @tag("internal")
    @task(3)
    def list_recipes(self) -> None:
        """GET /recipes — most common operation."""
        self.client.get("/recipes")

    @tag("internal")
    @task(2)
    def search_recipes(self) -> None:
        """GET /recipes/search — search by ingredient."""
        self.client.get(
            "/recipes/search",
            params={"ingredients": "pasta,tomato"},
        )

    @tag("internal")
    @task(1)
    def create_recipe(self) -> None:
        """POST /recipes — less frequent write."""
        self.client.post(
            "/recipes",
            json={
                "title": "Locust Recipe",
                "description": "Generated by load test",
                "ingredients": ["egg", "cheese"],
                "steps": ["Crack egg", "Add cheese", "Cook"],
            },
        )

    @tag("external")
    @task(1)
    def themealdb_meals_by_ingredient(self) -> None:
        """GET /external/themealdb/meals (TheMealDB filter.php)."""
        self.client.get(
            "/external/themealdb/meals",
            params={"ingredient": "chicken"},
            name="/external/themealdb/meals?ingredient=…",
        )

    @tag("external")
    @task(1)
    def themealdb_meal_detail(self) -> None:
        """GET /external/themealdb/meals/{id} (TheMealDB lookup.php)."""
        self.client.get(
            f"/external/themealdb/meals/{_MEALDB_SAMPLE_MEAL_ID}",
            name="/external/themealdb/meals/{meal_id}",
        )
